#region Copyright
///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Phoenix Contact GmbH & Co KG
//  This software is licensed under Apache-2.0
//
///////////////////////////////////////////////////////////////////////////////
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 
namespace PlcNext.Common.Templates.Field {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates", IsNullable=false)]
    public partial class FieldTemplates {
        
        private fieldTemplate[] fieldTemplateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldTemplate")]
        public fieldTemplate[] FieldTemplate {
            get {
                return this.fieldTemplateField;
            }
            set {
                this.fieldTemplateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public partial class fieldTemplate {
        
        private valueRestriction valueRestrictionField;
        
        private string nameField;
        
        private bool hasvalueField;
        
        private string defaultvalueField;
        
        private multiplicity multiplicityField;
        
        private string splitField;
        
        public fieldTemplate() {
            this.hasvalueField = false;
            this.defaultvalueField = "";
            this.multiplicityField = multiplicity.One;
            this.splitField = "|";
        }
        
        /// <remarks/>
        public valueRestriction ValueRestriction {
            get {
                return this.valueRestrictionField;
            }
            set {
                this.valueRestrictionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("has-value")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool hasvalue {
            get {
                return this.hasvalueField;
            }
            set {
                this.hasvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("default-value")]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string defaultvalue {
            get {
                return this.defaultvalueField;
            }
            set {
                this.defaultvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(multiplicity.One)]
        public multiplicity multiplicity {
            get {
                return this.multiplicityField;
            }
            set {
                this.multiplicityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("|")]
        public string split {
            get {
                return this.splitField;
            }
            set {
                this.splitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public partial class valueRestriction {
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private bool ignorecaseField;
        
        private string minlengthField;
        
        private string maxlengthField;
        
        private string lengthField;
        
        private whitespace whitespaceField;
        
        public valueRestriction() {
            this.ignorecaseField = false;
            this.minlengthField = "0";
            this.maxlengthField = "-1";
            this.lengthField = "-1";
            this.whitespaceField = whitespace.Preserve;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Enumeration", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Pattern", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ignore-case")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ignorecase {
            get {
                return this.ignorecaseField;
            }
            set {
                this.ignorecaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("min-length", DataType="nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string minlength {
            get {
                return this.minlengthField;
            }
            set {
                this.minlengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("max-length", DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string maxlength {
            get {
                return this.maxlengthField;
            }
            set {
                this.maxlengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(whitespace.Preserve)]
        public whitespace whitespace {
            get {
                return this.whitespaceField;
            }
            set {
                this.whitespaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Enumeration,
        
        /// <remarks/>
        Pattern,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public enum whitespace {
        
        /// <remarks/>
        Preserve,
        
        /// <remarks/>
        Replace,
        
        /// <remarks/>
        Collapse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public enum multiplicity {
        
        /// <remarks/>
        One,
        
        /// <remarks/>
        OneOrMore,
    }
}
