#region Copyright
///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Phoenix Contact GmbH & Co KG
//  This software is licensed under Apache-2.0
//
///////////////////////////////////////////////////////////////////////////////
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 
namespace PlcNext.Common.Templates.Format {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates", IsNullable=false)]
    public partial class FormatTemplates {
        
        private formatTemplate[] formatTemplateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatTemplate")]
        public formatTemplate[] FormatTemplate {
            get {
                return this.formatTemplateField;
            }
            set {
                this.formatTemplateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public partial class formatTemplate {
        
        private conditionalConversionFormat[] conditionalConversionField;
        
        private regexConversionFormat[] regexConversionField;
        
        private templateConversionFormat[] templateConversionField;
        
        private prefixSuffixFormat[] prefixField;
        
        private prefixSuffixFormat[] suffixField;
        
        private string[] splitField;
        
        private string nameField;
        
        private multiplicity multiplicityField;
        
        private string seperatorField;
        
        private string targetField;
        
        public formatTemplate() {
            this.multiplicityField = multiplicity.One;
            this.seperatorField = "";
            this.targetField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionalConversion")]
        public conditionalConversionFormat[] ConditionalConversion {
            get {
                return this.conditionalConversionField;
            }
            set {
                this.conditionalConversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegexConversion")]
        public regexConversionFormat[] RegexConversion {
            get {
                return this.regexConversionField;
            }
            set {
                this.regexConversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TemplateConversion")]
        public templateConversionFormat[] TemplateConversion {
            get {
                return this.templateConversionField;
            }
            set {
                this.templateConversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Prefix")]
        public prefixSuffixFormat[] Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Suffix")]
        public prefixSuffixFormat[] Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Split")]
        public string[] Split {
            get {
                return this.splitField;
            }
            set {
                this.splitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(multiplicity.One)]
        public multiplicity multiplicity {
            get {
                return this.multiplicityField;
            }
            set {
                this.multiplicityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string seperator {
            get {
                return this.seperatorField;
            }
            set {
                this.seperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public partial class conditionalConversionFormat {
        
        private string conditionField;
        
        private string templateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public partial class prefixSuffixFormat {
        
        private bool onlyaggregatedField;
        
        private string valueField;
        
        public prefixSuffixFormat() {
            this.onlyaggregatedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("only-aggregated")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool onlyaggregated {
            get {
                return this.onlyaggregatedField;
            }
            set {
                this.onlyaggregatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public partial class templateConversionFormat {
        
        private bool ignorecaseField;
        
        private string patternField;
        
        private string templateField;
        
        public templateConversionFormat() {
            this.ignorecaseField = false;
            this.patternField = ".*";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ignore-case")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ignorecase {
            get {
                return this.ignorecaseField;
            }
            set {
                this.ignorecaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(".*")]
        public string pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public partial class regexConversionFormat {
        
        private bool ignorecaseField;
        
        private string patternField;
        
        private string convertedField;
        
        public regexConversionFormat() {
            this.ignorecaseField = false;
            this.patternField = ".*";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ignore-case")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ignorecase {
            get {
                return this.ignorecaseField;
            }
            set {
                this.ignorecaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(".*")]
        public string pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string converted {
            get {
                return this.convertedField;
            }
            set {
                this.convertedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/clitemplates")]
    public enum multiplicity {
        
        /// <remarks/>
        One,
        
        /// <remarks/>
        OneOrMore,
    }
}
