#region Copyright
///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Phoenix Contact GmbH & Co KG
//  This software is licensed under Apache-2.0
//
///////////////////////////////////////////////////////////////////////////////
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace PlcNext.Common.Deploy.SolutionMapping {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.phoenixcontact.com/schema/solutionmappingschema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.phoenixcontact.com/schema/solutionmappingschema", IsNullable=false)]
    public partial class SolutionMappings {
        
        private SolutionMapping[] mappingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mapping")]
        public SolutionMapping[] Mapping {
            get {
                return this.mappingField;
            }
            set {
                this.mappingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.phoenixcontact.com/schema/solutionmappingschema")]
    public partial class SolutionMapping {
        
        private string engineerVersionRangeField;
        
        private string solutionVersionField;
        
        /// <remarks/>
        public string EngineerVersionRange {
            get {
                return this.engineerVersionRangeField;
            }
            set {
                this.engineerVersionRangeField = value;
            }
        }
        
        /// <remarks/>
        public string SolutionVersion {
            get {
                return this.solutionVersionField;
            }
            set {
                this.solutionVersionField = value;
            }
        }
    }
}
