#region Copyright
///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Phoenix Contact GmbH & Co KG
//  This software is licensed under Apache-2.0
//
///////////////////////////////////////////////////////////////////////////////
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace PlcNext.Common.Project {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.phoenixcontact.com/schema/projectconfiguration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.phoenixcontact.com/schema/projectconfiguration", IsNullable=false)]
    public partial class ProjectConfiguration {
        
        private string engineerVersionField;
        
        private string solutionVersionField;
        
        private string libraryVersionField;
        
        private string libraryDescriptionField;
        
        private string[] excludedFilesField;
        
        /// <remarks/>
        public string EngineerVersion {
            get {
                return this.engineerVersionField;
            }
            set {
                this.engineerVersionField = value;
            }
        }
        
        /// <remarks/>
        public string SolutionVersion {
            get {
                return this.solutionVersionField;
            }
            set {
                this.solutionVersionField = value;
            }
        }
        
        /// <remarks/>
        public string LibraryVersion {
            get {
                return this.libraryVersionField;
            }
            set {
                this.libraryVersionField = value;
            }
        }
        
        /// <remarks/>
        public string LibraryDescription {
            get {
                return this.libraryDescriptionField;
            }
            set {
                this.libraryDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("File", IsNullable=false)]
        public string[] ExcludedFiles {
            get {
                return this.excludedFilesField;
            }
            set {
                this.excludedFilesField = value;
            }
        }
    }
}
