#region Copyright
///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Phoenix Contact GmbH & Co KG
//  This software is licensed under Apache-2.0
//
///////////////////////////////////////////////////////////////////////////////
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlcNext.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingDescriptons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingDescriptons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlcNext.Common.SettingDescriptons", typeof(SettingDescriptons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always write an extended log.
        /// </summary>
        internal static string AlwaysWriteExtendedLog {
            get {
                return ResourceManager.GetString("AlwaysWriteExtendedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix of attributes.
        /// </summary>
        internal static string AttributePrefix {
            get {
                return ResourceManager.GetString("AttributePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the log file.
        /// </summary>
        internal static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the MS build files.
        /// </summary>
        internal static string MSBuildPath {
            get {
                return ResourceManager.GetString("MSBuildPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paths to the SDKs.
        /// </summary>
        internal static string SdkPaths {
            get {
                return ResourceManager.GetString("SdkPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the templates..
        /// </summary>
        internal static string TemplateLocations {
            get {
                return ResourceManager.GetString("TemplateLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system commands.
        /// </summary>
        internal static string UseSystemCommands {
            get {
                return ResourceManager.GetString("UseSystemCommands", resourceCulture);
            }
        }
    }
}
