#region Copyright
///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Phoenix Contact GmbH & Co KG
//  This software is licensed under Apache-2.0
//
///////////////////////////////////////////////////////////////////////////////
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PlcNext.Common.Tools.Security {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.phoenixcontact.com/schema/rsa-signature")]
    [System.Xml.Serialization.XmlRootAttribute("RSA-Signature", Namespace="http://www.phoenixcontact.com/schema/rsa-signature", IsNullable=false)]
    public partial class RSASignature {
        
        private byte[] rawSignatureField;
        
        private string hashAlgorithmField;
        
        private string rsaPaddingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RawSignature {
            get {
                return this.rawSignatureField;
            }
            set {
                this.rawSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string HashAlgorithm {
            get {
                return this.hashAlgorithmField;
            }
            set {
                this.hashAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        public string RsaPadding {
            get {
                return this.rsaPaddingField;
            }
            set {
                this.rsaPaddingField = value;
            }
        }
    }
}
